"""Emit rendered raster cells as Connect IQ bitmap resources."""

from __future__ import annotations

import json
import os
import shutil
import tempfile
import unicodedata
from typing import Iterable, List, Sequence

from .geom import BBox
from .osmread import DEFAULT_ATTRIBUTION, Way
from .raster import RasterFonts, RasterGrid, build_scene, grid_for, render_cell


def _atomic_write(path: str, text: str) -> None:
    """Atomically replace one generated UTF-8 text artifact."""
    directory = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(directory, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=directory,
        prefix=".%s." % os.path.basename(path),
        delete=False,
    )
    try:
        with handle:
            handle.write(text)
        os.replace(handle.name, path)
    except BaseException:
        try:
            os.unlink(handle.name)
        except FileNotFoundError:
            pass
        raise


def _resource_xml(grids: Sequence[RasterGrid]) -> str:
    lines = ["<resources>", "    <!-- GENERATED by tools/mappack. Do not edit. -->"]
    for grid in grids:
        for col in range(grid.cols):
            for row in range(grid.rows):
                resource_id = "r%d_%d_%d" % (grid.zoom, col, row)
                lines.append(
                    '    <bitmap id="%s" filename="tiles/%s.png" '
                    'scope="foreground" packingFormat="png" />'
                    % (resource_id, resource_id)
                )
    lines.extend(["</resources>", ""])
    return "\n".join(lines)


def _monkey_c_string(text: str) -> str:
    """Return a Monkey C string literal without altering valid text."""
    if any(unicodedata.category(character) == "Cc" for character in text):
        raise ValueError("pack name contains a control character")
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % escaped


def _zoom_lookup(lines: List[str], name: str, grids: Sequence[RasterGrid]) -> None:
    lines.append("    function %s(zoom) {" % name)
    for grid in grids:
        value = {
            "originX": grid.origin_x,
            "originY": grid.origin_y,
            "cols": grid.cols,
            "rows": grid.rows,
        }[name]
        lines.append("        if (zoom == %d) { return %d; }" % (grid.zoom, value))
    lines.extend(["        return null;", "    }", ""])


def _index_source(
    grids: Sequence[RasterGrid], bounds: BBox, name: str
) -> str:
    west, south, east, north = bounds
    center_lon = (west + east) / 2.0
    center_lat = (south + north) / 2.0
    lines = [
        "//",
        "// GENERATED FILE -- DO NOT EDIT.",
        "// Produced by tools/mappack. Regenerate with `make raster-demo` or",
        "// `make raster-pack`, according to the pack selected for this build.",
        "//",
        "",
        "module RasterMapIndex {",
        "    const TILE_SIZE = %d;" % grids[0].tile_size,
        "    const ZOOMS = [%s];" % ", ".join(str(grid.zoom) for grid in grids),
        "    const PACK_NAME = %s;" % _monkey_c_string(name),
        '    const ATTRIBUTION = "%s";' % DEFAULT_ATTRIBUTION,
        "    const WEST = %.7fd;" % west,
        "    const SOUTH = %.7fd;" % south,
        "    const EAST = %.7fd;" % east,
        "    const NORTH = %.7fd;" % north,
        "    const CENTER_LON = %.7fd;" % center_lon,
        "    const CENTER_LAT = %.7fd;" % center_lat,
        "    const HOME_LON = %.7fd;" % center_lon,
        "    const HOME_LAT = %.7fd;" % center_lat,
        "",
    ]

    for lookup in ("originX", "originY", "cols", "rows"):
        _zoom_lookup(lines, lookup, grids)

    lines.append("    function resourceAt(zoom, col, row) {")
    for grid in grids:
        lines.append(
            "        if (zoom == %d) { return resourceAt%d(col, row); }"
            % (grid.zoom, grid.zoom)
        )
    lines.extend(["        return null;", "    }", ""])

    for grid in grids:
        lines.append("    function resourceAt%d(col, row) {" % grid.zoom)
        lines.append(
            "        if (col < 0 || row < 0 || col >= %d || row >= %d) { return null; }"
            % (grid.cols, grid.rows)
        )
        lines.append("        var key = col * %d + row;" % grid.rows)
        lines.append("        switch (key) {")
        for col in range(grid.cols):
            for row in range(grid.rows):
                key = col * grid.rows + row
                lines.append(
                    "            case %d: return Rez.Drawables.r%d_%d_%d;"
                    % (key, grid.zoom, col, row)
                )
        lines.extend(["        }", "        return null;", "    }", ""])
    lines.extend(["}", ""])
    return "\n".join(lines)


def write_raster_pack(
    ways: Iterable[Way],
    bounds: BBox,
    zooms: Sequence[int],
    out_dir: str,
    index_path: str,
    fonts: RasterFonts,
    name: str = "raster",
):
    """Render and atomically index a deterministic two-zoom raster pack."""
    zoom_values = sorted(zooms)
    if zoom_values != [13, 15]:
        raise ValueError("raster packs require zooms 13 and 15")

    grids = [grid_for(bounds, zoom) for zoom in zoom_values]
    index_source = _index_source(grids, bounds, name)
    source_ways = tuple(ways)
    tiles_dir = os.path.join(out_dir, "tiles")
    if os.path.islink(tiles_dir) or os.path.isfile(tiles_dir):
        os.unlink(tiles_dir)
    elif os.path.isdir(tiles_dir):
        shutil.rmtree(tiles_dir)
    os.makedirs(tiles_dir, exist_ok=True)

    resource_count = 0
    for grid in grids:
        scene = build_scene(source_ways, grid.zoom, grid.tile_size)
        for col in range(grid.cols):
            for row in range(grid.rows):
                resource_id = "r%d_%d_%d" % (grid.zoom, col, row)
                path = os.path.join(tiles_dir, resource_id + ".png")
                render_cell(scene, grid, col, row, fonts).save(
                    path, format="PNG", optimize=True
                )
                resource_count += 1

    center = [(bounds[0] + bounds[2]) / 2.0, (bounds[1] + bounds[3]) / 2.0]
    manifest = {
        "attribution": DEFAULT_ATTRIBUTION,
        "bounds": list(bounds),
        "center": center,
        "grids": [
            {
                "cols": grid.cols,
                "originX": grid.origin_x,
                "originY": grid.origin_y,
                "rows": grid.rows,
                "zoom": grid.zoom,
            }
            for grid in grids
        ],
        "name": name,
        "resourceCount": resource_count,
        "tileSize": grids[0].tile_size,
        "zooms": zoom_values,
    }

    _atomic_write(os.path.join(out_dir, "mapdata.xml"), _resource_xml(grids))
    _atomic_write(
        os.path.join(out_dir, "pack.json"),
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    )
    _atomic_write(index_path, index_source)
    return manifest
